### ISSUE TITLE
add at the end of function 'CreateExtendedPlayer', above return self 

### ISSUE THREAD

**Issue by valvi1** [MGDev-McDo/mgd_gangbuilder#1]
dodne lo pondria esta parte

![image](https://github.com/user-attachments/assets/edb513cb-f741-4731-aa8f-458c73d3cd70)
![image](https://github.com/user-attachments/assets/f1d2e3a9-2864-4e7e-8f5a-b335e509436a)

**Comment by MGDev-McDo** [comment]
Al final de la función, después de todas las funciones del personaje (self.getName, ...)
En las proximidades de 890 líneas normalmente

![image](https://github.com/user-attachments/assets/78130f6a-6583-48b1-a61c-f3091b298c47)

**Comment by MGDev-McDo** [comment]
¿ Está bien para ti ? @valvi1
